# YOLO Training Configuration

training:
  epochs: 100
  img_size: 640
  batch_size: 16
  workers: 8
  patience: 50  # Early stopping patience
  
model:
  name: "best.pt"  # Base model to start from
  classes: 80  # Number of classes (will be updated based on dataset)
  
data:
  train_split: 0.8
  val_split: 0.2
  augmentation: true
  
optimization:
  optimizer: "SGD"
  lr0: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  
output:
  save_dir: "models/runs"
  save_period: 10  # Save checkpoint every N epochs
  
logging:
  wandb: false  # Set to true to enable Weights & Biases logging
  tensorboard: true